steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-central2-docker.pkg.dev/gcp-playground-440117/playground', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      "push",
      "europe-central2-docker.pkg.dev/gcp-playground-440117/playground",
    ]
serviceAccount: 'projects/gcp-playground-440117/serviceAccounts/cloud-build-mg@gcp-playground-440117.iam.gserviceaccount.com'
