name: CB

on:
  push:

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push image
        run: gcloud builds submit .

      - name: Authenticate Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Tag image
        run: gcloud artifacts docker tags add europe-central2-docker.pkg.dev/gcp-playground-440117/playground/image-123:cloudbuild europe-central2-docker.pkg.dev/gcp-playground-440117/playground/image-123:dupa
