name: GCP

on:
  push:

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Check Artifact Registry
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev
          docker build . -t europe-central2-docker.pkg.dev/gcp-playground-440117/playground

      - name: Push image
        run: docker push europe-central2-docker.pkg.dev/gcp-playground-440117/playground