name: GCP

on:
  workflow_dispatch:
#  push:

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: europe-central2-docker.pkg.dev/gcp-playground-440117/playground/image-123:youtube
          cache-from: type=gha
          cache-to: type=gha,mode=max
