name: Creating PR

on:
  push:
    branches: [dev]

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: HDBandit/gitflow-release-action@2.0.10
        with:
          command: start_finish
          tag: 1.0.0
          git_user: github-actions # Optional
          git_email: github-actions@github.com # Optional
          main_branch: main # Optional
          develop_branch: dev # Optional